name: mathpuzzles
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  shared_preferences: ^2.5.4
  google_fonts: ^6.3.3
  path_provider: ^2.1.2
  audioplayers: ^6.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.jpg"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/sfx/
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-VariableFont_GRAD,opsz,wght.ttf
    - family: Freehand
      fonts:
        - asset: assets/fonts/Freehand-Regular.ttf
